### ISSUE TITLE
Preserve URL Queries

### ISSUE THREAD

**Issue by williamchristophercooley** [beeman/ngx-scrollspy-angular-cli-demo#5]
When the # gets added for the anchoring on the page, whatever current url queries that are in the url are destroyed.

**Comment by beeman** [comment]
Hi William, thanks for your message. I did not look into the issue but I think this should be solved in this library https://github.com/JonnyBGod/ngx-scrollspy as this repo is just a demo.

**Comment by williamchristophercooley** [comment]
good point, posted an issue there :)

**Comment by beeman** [comment]
Cool, thanks!
